package CS203JavaDemoApp;

import java.io.*;
import javax.swing.*;
import java.awt.*;
import CSLibrary.*;
import CSLibrary.Message.*;
import CSLibrary.Constants.*;

/**
 *
 * @author gene.yeung
 */
public class MainMenuFrame extends javax.swing.JFrame {

    // <editor-fold defaultstate="collapsed" desc="Variable">
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Init">
    /** Creates new form MainMenuFrame */
    public MainMenuFrame() {
        initComponents();

        Main.ReaderXP = new HighLevelInterface();

        int result = Main.ReaderXP.Connect(Main.ipAddress, 30000);
        if (result != CSLibrary.Constants.Result.OK)
        {
            MessageBox.ErrorShow("RFID Connect Fail");
            Main.ReaderXP.Disconnect();
            System.exit(0);
        }

        Main.applicationSettings = Main.macAddress + "Settings.txt"; // each device has its own settings

        //Center the dialog
        Dimension size = getSize();
        setLocation((Main.screen.width - size.width)/2, (Main.screen.height - size.height)/2);

        this.setTitle(String.format("CS203 IP = %s, MAC = %s", Main.ipAddress, Main.macAddress));

        //Load Setting
        File file = new File(Main.applicationSettings);
        try
        {
            if(!file.exists()){
                file.createNewFile();
                SaveSettings();
                LoadSettings();
            }
            else
            {
                LoadSettings();
            }
        }
        catch(IOException ex){}

        String rfidVers = Main.ReaderXP.GetLibraryVersion().ToString();
        String FirmVers = Main.ReaderXP.GetFirmwareVersion().ToString();
        String CSVers = CSLibrary.Tools.Info.GetVersion().ToString();

        lbl_demeAppVer.setText(Main.demeAppVer);
        lbl_jCSLibraryVer.setText(CSVers);
        lbl_rfidLibVer.setText(rfidVers);
        lbl_firmwareVer.setText(FirmVers);

        UpdateSetting();

        this.setIconImage(new ImageIcon("CSL Logo.jpg").getImage());
    }

    private void UpdateSetting()
    {
        int[] link = new int[1];
        int[] power = new int[1];

        Main.ReaderXP.GetCurrentLinkProfile(link);
        Main.ReaderXP.GetPowerLevel(power);

        lbl_freqProfile.setText(Main.ReaderXP.SelectedRegionCodeName());
        if (Main.ReaderXP.IsFixedChannel())
        {
            lbl_fixedFreqTitle.setText("Fixed Frequency :");
            lbl_fixedFreq.setText(Double.toString(Main.ReaderXP.SelectedFrequencyBand())+" MHz");
        }
        else
        {
            lbl_fixedFreqTitle.setText("Frequency :");
            lbl_fixedFreq.setText("Hopping");
        }
        lbl_profile.setText(Integer.toString(link[0]));
        lbl_power.setText(Integer.toString(power[0]));
    }
    // </editor-fold>

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_kill = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_demeAppVer = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_power = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_profile = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_fixedFreqTitle = new javax.swing.JLabel();
        lbl_freqProfileTitle = new javax.swing.JLabel();
        lbl_rfidLibVer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_firmwareVer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_freqProfile = new javax.swing.JLabel();
        lbl_fixedFreq = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_jCSLibraryVer = new javax.swing.JLabel();
        btn_security = new javax.swing.JButton();
        btn_setup = new javax.swing.JButton();
        btn_geiger = new javax.swing.JButton();
        btn_inventory = new javax.swing.JButton();
        btn_readwrite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btn_kill.setBackground(new java.awt.Color(255, 0, 51));
        btn_kill.setFont(new java.awt.Font("Arial", 0, 18));
        btn_kill.setText("Kill");
        btn_kill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_killActionPerformed(evt);
            }
        });

        lbl_demeAppVer.setFont(new java.awt.Font("Arial", 0, 14));
        lbl_demeAppVer.setText("0.0.0");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel9.setText("Demo App Ver :");

        lbl_power.setFont(new java.awt.Font("Arial", 0, 14));
        lbl_power.setText("300");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel10.setText("Power :");

        lbl_profile.setFont(new java.awt.Font("Arial", 0, 14));
        lbl_profile.setText("2");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel11.setText("Profile :");

        lbl_fixedFreqTitle.setFont(new java.awt.Font("Arial", 0, 14));
        lbl_fixedFreqTitle.setText("Fixed Frequency :");

        lbl_freqProfileTitle.setFont(new java.awt.Font("Arial", 0, 14));
        lbl_freqProfileTitle.setText("Frequency Profile :");

        lbl_rfidLibVer.setFont(new java.awt.Font("Arial", 0, 14));
        lbl_rfidLibVer.setText("0.0.0");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel4.setText("RFID Lib Ver :");

        lbl_firmwareVer.setFont(new java.awt.Font("Arial", 0, 14));
        lbl_firmwareVer.setText("0.0.0");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel5.setText("Firmware Ver :");

        lbl_freqProfile.setFont(new java.awt.Font("Arial", 0, 14));
        lbl_freqProfile.setText("0");

        lbl_fixedFreq.setFont(new java.awt.Font("Arial", 0, 14));
        lbl_fixedFreq.setText("0");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel12.setText("JCSLibrary Ver :");

        lbl_jCSLibraryVer.setFont(new java.awt.Font("Arial", 0, 14));
        lbl_jCSLibraryVer.setText("0.0.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_freqProfileTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(lbl_fixedFreqTitle, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_demeAppVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_jCSLibraryVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_firmwareVer, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addComponent(lbl_rfidLibVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(30, 30, 30)))
                    .addComponent(lbl_freqProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(lbl_fixedFreq, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(lbl_profile, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(lbl_power, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_freqProfileTitle)
                            .addComponent(lbl_freqProfile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_fixedFreqTitle)
                            .addComponent(lbl_fixedFreq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lbl_profile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lbl_power)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_demeAppVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_jCSLibraryVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_rfidLibVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_firmwareVer)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        btn_security.setBackground(new java.awt.Color(255, 153, 153));
        btn_security.setFont(new java.awt.Font("Arial", 0, 18));
        btn_security.setText("Security");
        btn_security.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_securityActionPerformed(evt);
            }
        });

        btn_setup.setBackground(new java.awt.Color(51, 153, 255));
        btn_setup.setFont(new java.awt.Font("Arial", 0, 18));
        btn_setup.setText("Setup");
        btn_setup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setupActionPerformed(evt);
            }
        });

        btn_geiger.setBackground(new java.awt.Color(102, 255, 102));
        btn_geiger.setFont(new java.awt.Font("Arial", 0, 18));
        btn_geiger.setText("Geiger");
        btn_geiger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geigerActionPerformed(evt);
            }
        });

        btn_inventory.setBackground(new java.awt.Color(204, 204, 255));
        btn_inventory.setFont(new java.awt.Font("Arial", 0, 18));
        btn_inventory.setText("Inventory");
        btn_inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventoryActionPerformed(evt);
            }
        });

        btn_readwrite.setBackground(new java.awt.Color(153, 255, 255));
        btn_readwrite.setFont(new java.awt.Font("Arial", 0, 18));
        btn_readwrite.setText("Read Write");
        btn_readwrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readwriteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_setup, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btn_kill, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btn_security, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btn_geiger, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_readwrite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_inventory, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_readwrite, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_geiger, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_security, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_kill, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_setup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Setting">
    public static boolean SaveSettings()
    {
        Settings.Channel_number = Main.ReaderXP.SelectedChannel();
        Settings.Lbt = Main.ReaderXP.LBT_ON() == LBT.ON;
        Settings.Link_profile = Main.ReaderXP.SelectedLinkProfile();
        Settings.Power = Main.ReaderXP.SelectedPowerLevel();
        Settings.Region = Main.ReaderXP.SelectedRegionCode();
        Settings.FixedChannel = Main.ReaderXP.IsFixedChannel();
        return Settings.Save();
    }

    public static void LoadSettings()
    {
        Settings.Load();
        //Apply previous configuration
        if (Main.ReaderXP.SetPowerLevel(Settings.Power) != CSLibrary.Constants.Result.OK)
        {
            MessageBox.ErrorShow("SetPowerLevel rc = " + Integer.toString(Main.ReaderXP.LastResultCode()));
            return;
        }
        if (Main.ReaderXP.SetCurrentLinkProfile(Settings.Link_profile) != CSLibrary.Constants.Result.OK)
        {
            MessageBox.ErrorShow("SetCurrentLinkProfile rc = " + Integer.toString(Main.ReaderXP.LastResultCode()));
            return;
        }
        if (Settings.FixedChannel)
        {
            if (Main.ReaderXP.SetFixedChannel(Settings.Region, Settings.Channel_number, Settings.Lbt ? LBT.ON : LBT.OFF) != CSLibrary.Constants.Result.OK)
            {
                MessageBox.ErrorShow("SetFixedChannel rc = " + Integer.toString(Main.ReaderXP.LastResultCode()));
                return;
            }
        }
        else
        {
            if (Main.ReaderXP.SetHoppingChannels(Settings.Region) != CSLibrary.Constants.Result.OK)
            {
                MessageBox.ErrorShow("SetHoppingChannels rc = " + Integer.toString(Main.ReaderXP.LastResultCode()));
                return;
            }
        }

        switch (Settings.singulation)
        {
            case SingulationAlgorithm.DYNAMICQ:
                if (Main.ReaderXP.SetSingulationAlgorithmParms(Settings.singulation, Settings.dynamicQ) != CSLibrary.Constants.Result.OK)
                {
                    MessageBox.ErrorShow("SetSingulationAlgorithmParms rc = " + Integer.toString(Main.ReaderXP.LastResultCode()));
                    return;
                }
                break;
            case SingulationAlgorithm.DYNAMICQ_ADJUST:
                if (Main.ReaderXP.SetSingulationAlgorithmParms(Settings.singulation, Settings.dynamicQAdj) != CSLibrary.Constants.Result.OK)
                {
                    MessageBox.ErrorShow("SetSingulationAlgorithmParms rc = " + Integer.toString(Main.ReaderXP.LastResultCode()));
                    return;
                }
                break;
            case SingulationAlgorithm.DYNAMICQ_THRESH:
                if (Main.ReaderXP.SetSingulationAlgorithmParms(Settings.singulation, Settings.dynamicQThres) != CSLibrary.Constants.Result.OK)
                {
                    MessageBox.ErrorShow("SetSingulationAlgorithmParms rc = " + Integer.toString(Main.ReaderXP.LastResultCode()));
                    return;
                }
                break;
            case SingulationAlgorithm.FIXEDQ:
                if (Main.ReaderXP.SetSingulationAlgorithmParms(Settings.singulation, Settings.fixedQ) != CSLibrary.Constants.Result.OK)
                {
                    MessageBox.ErrorShow("SetSingulationAlgorithmParms rc = " + Integer.toString(Main.ReaderXP.LastResultCode()));
                    return;
                }
                break;
        }
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="UI Handle">
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Main.ReaderXP.Disconnect();
        new NetFinderFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_killActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_killActionPerformed
        new TagKillDialog(null, true).setVisible(true);
}//GEN-LAST:event_btn_killActionPerformed

    private void btn_securityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_securityActionPerformed
        new TagSecurityDialog(null, true).setVisible(true);
}//GEN-LAST:event_btn_securityActionPerformed

    private void btn_setupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setupActionPerformed
        new SetupDialog(null, true).setVisible(true);
        UpdateSetting();
}//GEN-LAST:event_btn_setupActionPerformed

    private void btn_geigerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geigerActionPerformed
        new TagGeigerSearchDialog(null, true).setVisible(true);
}//GEN-LAST:event_btn_geigerActionPerformed

    private void btn_inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventoryActionPerformed
        new TagInventoryDialog(null, true).setVisible(true);
}//GEN-LAST:event_btn_inventoryActionPerformed

    private void btn_readwriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readwriteActionPerformed
        new TagReadWriteDialog(null, true).setVisible(true);
}//GEN-LAST:event_btn_readwriteActionPerformed
    // </editor-fold>
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_geiger;
    private javax.swing.JButton btn_inventory;
    private javax.swing.JButton btn_kill;
    private javax.swing.JButton btn_readwrite;
    private javax.swing.JButton btn_security;
    private javax.swing.JButton btn_setup;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_demeAppVer;
    private javax.swing.JLabel lbl_firmwareVer;
    private javax.swing.JLabel lbl_fixedFreq;
    private javax.swing.JLabel lbl_fixedFreqTitle;
    private javax.swing.JLabel lbl_freqProfile;
    private javax.swing.JLabel lbl_freqProfileTitle;
    private javax.swing.JLabel lbl_jCSLibraryVer;
    private javax.swing.JLabel lbl_power;
    private javax.swing.JLabel lbl_profile;
    private javax.swing.JLabel lbl_rfidLibVer;
    // End of variables declaration//GEN-END:variables

}
