package CS203JavaDemoApp;

import java.awt.*;
import javax.swing.table.*;
import CSLibrary.Events.*;
import CSLibrary.Constants.*;
import CSLibrary.Structures.*;
import CSLibrary.Tools.*;
import CSLibrary.Message.*;

/**
 *
 * @author gene.yeung
 */
public class TagKillDialog extends javax.swing.JDialog implements StateChangedEventListener, AsyncCallbackEventListener, AccessCompletedEventListener {

    // <editor-fold defaultstate="collapsed" desc="Variable">
    private class Opts{
        final public static int UNKNOWN = -1;
        final public static int TAG_SEARCH = 0;
        final public static int TAG_KILL = 1;
    }
    private boolean m_result = true;
    private int m_opt = Opts.UNKNOWN;
    private DefaultTableModel searchTableModel;
    private String selectedPC = "";
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Init">
    /** Creates new form TagKillDialog */
    public TagKillDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //Center the dialog
        Dimension size = getSize();
        setLocation((Main.screen.width - size.width)/2, (Main.screen.height - size.height)/2);

        searchTableModel = (DefaultTableModel)table_search.getModel();
    }
    // </editor-fold>

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Panel_SelectTag = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_search = new javax.swing.JTable();
        btn_search = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        tf_selectedEPC = new javax.swing.JTextField();
        Panel_ReadAll = new javax.swing.JPanel();
        lbl_pcepctext = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_kill = new javax.swing.JButton();
        lbl_pcepc = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_kill = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Kill Tag");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(318, 232));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        Panel_SelectTag.setPreferredSize(new java.awt.Dimension(308, 186));

        table_search.setAutoCreateRowSorter(true);
        table_search.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        table_search.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PC", "EPC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_search.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_search.getTableHeader().setReorderingAllowed(false);
        table_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_searchMousePressed(evt);
            }
        });
        table_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_searchKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_search);
        table_search.getColumnModel().getColumn(0).setPreferredWidth(40);
        table_search.getColumnModel().getColumn(1).setPreferredWidth(280);

        btn_search.setBackground(java.awt.Color.green);
        btn_search.setFont(new java.awt.Font("Arial", 0, 18));
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_clear.setBackground(java.awt.Color.orange);
        btn_clear.setFont(new java.awt.Font("Arial", 0, 18));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        tf_selectedEPC.setBackground(java.awt.Color.pink);
        tf_selectedEPC.setFont(new java.awt.Font("Arial", 0, 14));

        org.jdesktop.layout.GroupLayout Panel_SelectTagLayout = new org.jdesktop.layout.GroupLayout(Panel_SelectTag);
        Panel_SelectTag.setLayout(Panel_SelectTagLayout);
        Panel_SelectTagLayout.setHorizontalGroup(
            Panel_SelectTagLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Panel_SelectTagLayout.createSequentialGroup()
                .addContainerGap()
                .add(btn_search)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn_clear)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(tf_selectedEPC, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        Panel_SelectTagLayout.setVerticalGroup(
            Panel_SelectTagLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, Panel_SelectTagLayout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(Panel_SelectTagLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn_search)
                    .add(btn_clear)
                    .add(tf_selectedEPC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Select Tag", Panel_SelectTag);

        Panel_ReadAll.setPreferredSize(new java.awt.Dimension(308, 202));

        lbl_pcepctext.setFont(new java.awt.Font("Arial", 0, 18));
        lbl_pcepctext.setText("PC-EPC");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel5.setText("Kill Password");

        btn_kill.setBackground(java.awt.Color.green);
        btn_kill.setFont(new java.awt.Font("Arial", 0, 18));
        btn_kill.setText("Kill");
        btn_kill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_killActionPerformed(evt);
            }
        });

        lbl_pcepc.setFont(new java.awt.Font("Arial", 0, 18));
        lbl_pcepc.setForeground(java.awt.Color.blue);
        lbl_pcepc.setText("0000-000000000000000000000000");

        jPanel1.setBackground(java.awt.Color.red);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Warning");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tag will be destoryed permanently.");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        try {
            tf_kill.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tf_kill.setText("00000000");
        tf_kill.setFont(new java.awt.Font("Arial", 0, 18));

        org.jdesktop.layout.GroupLayout Panel_ReadAllLayout = new org.jdesktop.layout.GroupLayout(Panel_ReadAll);
        Panel_ReadAll.setLayout(Panel_ReadAllLayout);
        Panel_ReadAllLayout.setHorizontalGroup(
            Panel_ReadAllLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Panel_ReadAllLayout.createSequentialGroup()
                .add(Panel_ReadAllLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Panel_ReadAllLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(Panel_ReadAllLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(Panel_ReadAllLayout.createSequentialGroup()
                                .add(lbl_pcepctext)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(lbl_pcepc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 301, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(Panel_ReadAllLayout.createSequentialGroup()
                        .add(63, 63, 63)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tf_kill, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(Panel_ReadAllLayout.createSequentialGroup()
                        .add(172, 172, 172)
                        .add(btn_kill, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Panel_ReadAllLayout.setVerticalGroup(
            Panel_ReadAllLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Panel_ReadAllLayout.createSequentialGroup()
                .addContainerGap()
                .add(Panel_ReadAllLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbl_pcepctext)
                    .add(lbl_pcepc))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(51, 51, 51)
                .add(Panel_ReadAllLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(tf_kill, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(btn_kill)
                .add(69, 69, 69))
        );

        jTabbedPane1.addTab("Kill Tag", Panel_ReadAll);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Event Handle">
    private void AttachCallback(boolean en)
    {
        if (en)
        {
            Main.ReaderXP.addStateChangedEventListener(this);
            Main.ReaderXP.addAsyncCallbackEventListener(this);
            Main.ReaderXP.addTagAccessCompletedEventListener(this);
        }
        else
        {
            Main.ReaderXP.removeStateChangedEventListener(this);
            Main.ReaderXP.removeAsyncCallbackEventListener(this);
            Main.ReaderXP.removeTagAccessCompletedEventListener(this);
        }
    }

    //callback function
    public void StateChangedEvent(StateChangedEventArgs ev)
    {
        switch (ev.state)
        {
            case RFState.IDLE:
                SetSearchButtonState(false);
                switch (m_opt)
                {
                    case Opts.TAG_SEARCH:
                        break;
                    case Opts.TAG_KILL:
                        break;
                }
                break;
            case RFState.BUSY:
                switch (m_opt)
                {
                    case Opts.TAG_SEARCH:
                        SetSearchButtonState(true);
                        break;
                    case Opts.TAG_KILL:
                        break;
                }
                break;
            case RFState.STOPPING:
                break;
            case RFState.NOT_INITIALIZED:
                break;
        }
    }

    public void AsyncCallbackEvent(AsyncCallbackEventArgs ev)
    {
        if (ev.type == CallbackType.TAG_INVENTORY)
        {
            TagCallbackInfo record = ev.info;

            Object[] entry = new Object[] {record.pc.ToString(), record.epc.ToString()};
            searchTableModel.addRow(entry);
            Sound.Beep(2000, 10);
        }
    }

    public void TagAccessCompletedEvent(AccessCompletedEventArgs ev)
    {
        if (ev.access == TagAccess.KILL)
        {
            if (ev.success && m_result)
            {
                MessageBox.InfoShow("Kill Success!");
            }
            else
            {
                MessageBox.InfoShow("Kill Fail!");
            }
        }
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Other Handle">
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        AttachCallback(true);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (Main.ReaderXP.GetState() != RFState.IDLE)
        {
            Main.ReaderXP.StopOperation(true);
        }
        while(Main.ReaderXP.GetState() != RFState.IDLE)
        {
            try {
                Thread.sleep(100);
            }
            catch(InterruptedException e) {}
        }
        AttachCallback(false);
        evt.getWindow().dispose();
    }//GEN-LAST:event_formWindowClosing

    private void table_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_searchKeyReleased
        table_searchMousePressed(null);
    }//GEN-LAST:event_table_searchKeyReleased

    private void table_searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_searchMousePressed
        int i = table_search.getSelectedRow();
        tf_selectedEPC.setText(table_search.getValueAt(i, 1).toString());
        selectedPC = table_search.getValueAt(i, 0).toString();
    }//GEN-LAST:event_table_searchMousePressed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        if (Main.ReaderXP.GetState() == RFState.IDLE) {
            Clear(Opts.TAG_SEARCH);
            Start();
        } else {
            Stop();
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        Clear(Opts.TAG_SEARCH);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_killActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_killActionPerformed
        if (Main.ReaderXP.GetState() == RFState.IDLE) {
            m_opt = Opts.TAG_KILL;

            btn_kill.setText("Stop");
            btn_kill.setBackground(java.awt.Color.red);

            Main.ReaderXP.GetOptions().TagSelected.flags = SelectMaskFlags.ENABLE_PC_MASK;
            Main.ReaderXP.GetOptions().TagSelected.epcMask = new S_MASK(selectedPC + tf_selectedEPC.getText());
            Main.ReaderXP.GetOptions().TagSelected.epcMaskLength = Main.ReaderXP.GetOptions().TagSelected.epcMask.Length()*8;
            if (Main.ReaderXP.StartOperation(Operation.TAG_SELECTED, true) != Result.OK)
            {
                MessageBox.ErrorShow("Selected tag failed");
                return;
            }

            Main.ReaderXP.GetOptions().TagKill.retryCount = 0;
            Main.ReaderXP.GetOptions().TagKill.accessPassword = 0;
            Main.ReaderXP.GetOptions().TagKill.killPassword = (int)Long.parseLong(tf_kill.getText(), 16);
            Main.ReaderXP.GetOptions().TagKill.flags = SelectFlags.SELECT;
            Main.ReaderXP.StartOperation(Operation.TAG_KILL, true);

            btn_kill.setText("Kill");
            btn_kill.setBackground(java.awt.Color.green);
        } else {
            MessageBox.WarningShow("Reader is busy now, please try later.");
        }
    }//GEN-LAST:event_btn_killActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (Main.ReaderXP.GetState() != RFState.IDLE) {
            Main.ReaderXP.StopOperation(true);
        }
        int selected = jTabbedPane1.getSelectedIndex();
        m_opt = selected;
        if (selected != Opts.TAG_SEARCH && tf_selectedEPC.getText().equals("")) {
            MessageBox.ErrorShow("Please select or input a tag ID first.");
            jTabbedPane1.setSelectedIndex(0);
            return;
        }
        switch(selected) {
            case Opts.TAG_SEARCH:
                break;
            case Opts.TAG_KILL:
                String text = selectedPC + "-" + tf_selectedEPC.getText();
                lbl_pcepc.setText(text);
                lbl_pcepc.setToolTipText(text);
                break;
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged
   
    private void Start()
    {
        if (Main.ReaderXP.GetState() == RFState.IDLE)
        {
            m_opt = Opts.TAG_SEARCH;
            Main.ReaderXP.SetOperationMode(Settings.custInventory_continuous ? RadioOperationMode.CONTINUOUS : RadioOperationMode.NONCONTINUOUS);
            Main.ReaderXP.SetTagGroup(Settings.tagGroup);
            Main.ReaderXP.SetSingulationAlgorithmParms(Settings.singulation, Settings.GetSingulationAlg());

            Main.ReaderXP.GetOptions().TagInventory.flags = SelectFlags.ZERO;
            Main.ReaderXP.StartOperation(Operation.TAG_INVENTORY, Settings.custInventory_blocking_mode);
        }
    }
    private void Stop()
    {
        if (Main.ReaderXP.GetState() == RFState.BUSY)
        {
            Main.ReaderXP.StopOperation(true);
        }
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="UI Update">
    private void Clear(int tab)
    {
        switch (tab)
        {
            case Opts.TAG_SEARCH:
                int len = searchTableModel.getRowCount();
                if (len > 0)
                {
                    for (int i = len-1; i >= 0; i--)
                        searchTableModel.removeRow(i);
                }
                tf_selectedEPC.setText("");
                break;
            case Opts.TAG_KILL:
                break;
        }
    }
    private void SetSearchButtonState(boolean searching)
    {
        if (searching)
        {
            btn_search.setText("Stop");
            btn_search.setBackground(java.awt.Color.red);
            btn_clear.setEnabled(false);
        }
        else
        {
            btn_search.setText("Search");
            btn_search.setBackground(java.awt.Color.green);
            btn_clear.setEnabled(true);
        }
    }
    // </editor-fold>

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TagKillDialog dialog = new TagKillDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_ReadAll;
    private javax.swing.JPanel Panel_SelectTag;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_kill;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_pcepc;
    private javax.swing.JLabel lbl_pcepctext;
    private javax.swing.JTable table_search;
    private javax.swing.JFormattedTextField tf_kill;
    private javax.swing.JTextField tf_selectedEPC;
    // End of variables declaration//GEN-END:variables

}
